name: Gradle CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install Chrome
      run: sudo apt-get install -y google-chrome-stable  # Ensures Chrome is installed

    - name: Check Chrome version
      run: google-chrome --version

    - name: Check ChromeDriver version
      run: chromedriver --version

    - name: Start xvfb (virtual display)
      run: | 
            sudo apt-get install -y xvfb
            Xvfb :99 -ac &
            export DISPLAY=:99

    - name: Build and Test with Gradle
      run: ./gradlew clean build -Dwebdriver.chrome.args="--headless" --stacktrace --info --warning-mode all

    - name: Set up JDK 20
      uses: actions/setup-java@v4
      with:
        java-version: '20'
        distribution: 'adopt'
        
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Build with Gradle
      run: ./gradlew build --stacktrace --info --warning-mode all
