name: Gradle CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 20
      uses: actions/setup-java@v4
      with:
          java-version: '20'
          distribution: 'adopt'
    
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libgbm-dev

    - name: Build with Gradle
      run: ./gradlew build

    - name: Build with Gradle
      run: ./gradlew test --info --stacktrace
