name: Gradle CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Chrome
      run: sudo apt-get install -y google-chrome-stable  # Ensure Chrome is installed

    - name: Check Chrome version
      run: google-chrome --version

    - name: Check ChromeDriver version
      run: chromedriver --version

    - name: Start xvfb (virtual display)
      run: | 
        sudo apt-get install -y xvfb
        Xvfb :99 -ac &
        export DISPLAY=:99

    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build and Test with Gradle
      run: ./gradlew clean build --stacktrace --info --warning-mode all
